// This file is automatically generated by flutter_rust_bridge v2, so please do not edit it.
// [@generated by flutter_rust_bridge]
// ignore_for_file: unused_import, unused_element, unused_field

import 'dart:convert' as convert;
import 'dart:ffi' as ffi;

/// Native C layout for EngineStatus matching EngineStatusC in Rust.
final class EngineStatusC extends ffi.Struct {
  @ffi.Bool()
  external bool isInitialized;

  @ffi.UintPtr()
  external int totalMemoryAllocated;

  @ffi.UintPtr()
  external int arenaCapacity;

  @ffi.Uint64()
  external int frameIndex;

  external ffi.Pointer<ffi.Char> statusMessage;
  external ffi.Pointer<ffi.Char> coreVersion;
  external ffi.Pointer<ffi.Char> allocatorName;
}

/// Helper function to decode null-terminated C-strings from native memory.
String readCString(ffi.Pointer<ffi.Char> ptr) {
  if (ptr == ffi.nullptr) return '';
  final p = ptr.cast<ffi.Uint8>();
  final units = <int>[];
  int offset = 0;
  while (true) {
    final byte = p[offset++];
    if (byte == 0) break;
    units.add(byte);
  }
  return const convert.Utf8Decoder().convert(units);
}

/// FFI types for raw native calls
typedef _WireStartEngineSyncC = ffi.Pointer<EngineStatusC> Function();
typedef _WireStartEngineSyncDart = ffi.Pointer<EngineStatusC> Function();

typedef _WireAllocateBufferC = ffi.Pointer<ffi.Uint8> Function(ffi.UintPtr);
typedef _WireAllocateBufferDart = ffi.Pointer<ffi.Uint8> Function(int);

typedef _WireFreeBufferC = ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr);
typedef _WireFreeBufferDart = void Function(ffi.Pointer<ffi.Uint8>, int);

typedef _WireFreeBufferAutoC = ffi.Void Function(ffi.Pointer<ffi.Uint8>);
typedef _WireFreeBufferAutoDart = void Function(ffi.Pointer<ffi.Uint8>);

typedef _WireGetStatusC = ffi.Pointer<EngineStatusC> Function();
typedef _WireGetStatusDart = ffi.Pointer<EngineStatusC> Function();

typedef _WireFreeStatusC = ffi.Void Function(ffi.Pointer<EngineStatusC>);
typedef _WireFreeStatusDart = void Function(ffi.Pointer<EngineStatusC>);

typedef _WireVerifySentinelsC = ffi.Bool Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr);
typedef _WireVerifySentinelsDart = bool Function(ffi.Pointer<ffi.Uint8>, int);

typedef _WireSharedBufNewC = ffi.Pointer<ffi.Void> Function(ffi.UintPtr);
typedef _WireSharedBufNewDart = ffi.Pointer<ffi.Void> Function(int);

typedef _WireSharedBufFreeC = ffi.Void Function(ffi.Pointer<ffi.Void>);
typedef _WireSharedBufFreeDart = void Function(ffi.Pointer<ffi.Void>);

typedef _WireSharedBufLenC = ffi.UintPtr Function(ffi.Pointer<ffi.Void>);
typedef _WireSharedBufLenDart = int Function(ffi.Pointer<ffi.Void>);

typedef _WireSharedBufPtrAddrC = ffi.UintPtr Function(ffi.Pointer<ffi.Void>);
typedef _WireSharedBufPtrAddrDart = int Function(ffi.Pointer<ffi.Void>);

typedef _WireSharedBufReadByteC = ffi.Uint8 Function(ffi.Pointer<ffi.Void>, ffi.UintPtr);
typedef _WireSharedBufReadByteDart = int Function(ffi.Pointer<ffi.Void>, int);

typedef _WireSharedBufWriteByteC = ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.UintPtr, ffi.Uint8);
typedef _WireSharedBufWriteByteDart = void Function(ffi.Pointer<ffi.Void>, int, int);

/// Low-level platform binding interface using dart:ffi to invoke compiled Rust C-ABI symbols.
class RustLibPlatform {
  final ffi.DynamicLibrary? dylib;

  _WireStartEngineSyncDart? _startEngineSync;
  _WireAllocateBufferDart? _allocateEngineBuffer;
  _WireFreeBufferDart? _freeEngineBuffer;
  _WireFreeBufferAutoDart? _freeEngineBufferAuto;
  _WireGetStatusDart? _getEngineStatus;
  _WireFreeStatusDart? _freeEngineStatus;
  _WireVerifySentinelsDart? _verifyBufferSentinels;
  _WireSharedBufNewDart? _sharedBufNew;
  _WireSharedBufFreeDart? _sharedBufFree;
  _WireSharedBufLenDart? _sharedBufLen;
  _WireSharedBufPtrAddrDart? _sharedBufPtrAddr;
  _WireSharedBufReadByteDart? _sharedBufReadByte;
  _WireSharedBufWriteByteDart? _sharedBufWriteByte;

  ffi.Pointer<ffi.NativeFinalizerFunction>? _freeBufferAutoFnPtr;
  ffi.Pointer<ffi.NativeFinalizerFunction>? _sharedBufFreeFnPtr;

  RustLibPlatform(this.dylib) {
    if (dylib != null) {
      _initBindings(dylib!);
    }
  }

  void _initBindings(ffi.DynamicLibrary lib) {
    try {
      _startEngineSync = lib
          .lookupFunction<_WireStartEngineSyncC, _WireStartEngineSyncDart>(
              'wire__crate__api__engine__start_engine_sync');
    } catch (_) {}

    try {
      _allocateEngineBuffer = lib
          .lookupFunction<_WireAllocateBufferC, _WireAllocateBufferDart>(
              'wire__crate__api__engine__allocate_engine_buffer');
    } catch (_) {}

    try {
      _freeEngineBuffer = lib
          .lookupFunction<_WireFreeBufferC, _WireFreeBufferDart>(
              'wire__crate__api__engine__free_engine_buffer');
    } catch (_) {}

    try {
      _freeEngineBufferAuto = lib
          .lookupFunction<_WireFreeBufferAutoC, _WireFreeBufferAutoDart>(
              'wire__crate__api__engine__free_engine_buffer_auto');
      _freeBufferAutoFnPtr = lib.lookup<ffi.NativeFinalizerFunction>(
          'wire__crate__api__engine__free_engine_buffer_auto');
    } catch (_) {}

    try {
      _getEngineStatus = lib
          .lookupFunction<_WireGetStatusC, _WireGetStatusDart>(
              'wire__crate__api__engine__get_engine_status');
    } catch (_) {}

    try {
      _freeEngineStatus = lib
          .lookupFunction<_WireFreeStatusC, _WireFreeStatusDart>(
              'wire__crate__api__engine__free_engine_status');
    } catch (_) {}

    try {
      _verifyBufferSentinels = lib
          .lookupFunction<_WireVerifySentinelsC, _WireVerifySentinelsDart>(
              'wire__crate__api__engine__verify_buffer_sentinels');
    } catch (_) {}

    try {
      _sharedBufNew = lib
          .lookupFunction<_WireSharedBufNewC, _WireSharedBufNewDart>(
              'wire__crate__api__engine__shared_frame_buffer_new');
    } catch (_) {}

    try {
      _sharedBufFree = lib
          .lookupFunction<_WireSharedBufFreeC, _WireSharedBufFreeDart>(
              'wire__crate__api__engine__shared_frame_buffer_free');
      _sharedBufFreeFnPtr = lib.lookup<ffi.NativeFinalizerFunction>(
          'wire__crate__api__engine__shared_frame_buffer_free');
    } catch (_) {}

    try {
      _sharedBufLen = lib
          .lookupFunction<_WireSharedBufLenC, _WireSharedBufLenDart>(
              'wire__crate__api__engine__shared_frame_buffer_len');
    } catch (_) {}

    try {
      _sharedBufPtrAddr = lib
          .lookupFunction<_WireSharedBufPtrAddrC, _WireSharedBufPtrAddrDart>(
              'wire__crate__api__engine__shared_frame_buffer_ptr_address');
    } catch (_) {}

    try {
      _sharedBufReadByte = lib
          .lookupFunction<_WireSharedBufReadByteC, _WireSharedBufReadByteDart>(
              'wire__crate__api__engine__shared_frame_buffer_read_byte');
    } catch (_) {}

    try {
      _sharedBufWriteByte = lib
          .lookupFunction<_WireSharedBufWriteByteC, _WireSharedBufWriteByteDart>(
              'wire__crate__api__engine__shared_frame_buffer_write_byte');
    } catch (_) {}
  }

  bool get hasNativeBindings => dylib != null && _allocateEngineBuffer != null;

  ffi.Pointer<ffi.NativeFinalizerFunction>? get freeBufferAutoFnPtr => _freeBufferAutoFnPtr;
  ffi.Pointer<ffi.NativeFinalizerFunction>? get sharedBufFreeFnPtr => _sharedBufFreeFnPtr;

  ffi.Pointer<EngineStatusC>? startEngineSyncRaw() => _startEngineSync?.call();

  ffi.Pointer<ffi.Uint8>? allocateBufferRaw(int sizeBytes) {
    return _allocateEngineBuffer?.call(sizeBytes);
  }

  void freeBufferRaw(ffi.Pointer<ffi.Uint8> ptr, int sizeBytes) {
    _freeEngineBuffer?.call(ptr, sizeBytes);
  }

  void freeBufferAutoRaw(ffi.Pointer<ffi.Uint8> ptr) {
    _freeEngineBufferAuto?.call(ptr);
  }

  ffi.Pointer<EngineStatusC>? getStatusRaw() => _getEngineStatus?.call();
  void freeStatusRaw(ffi.Pointer<EngineStatusC> ptr) => _freeEngineStatus?.call(ptr);

  bool verifyBufferSentinelsRaw(ffi.Pointer<ffi.Uint8> ptr, int len) {
    return _verifyBufferSentinels?.call(ptr, len) ?? false;
  }

  ffi.Pointer<ffi.Void>? sharedBufNewRaw(int sizeBytes) => _sharedBufNew?.call(sizeBytes);
  void sharedBufFreeRaw(ffi.Pointer<ffi.Void> ptr) => _sharedBufFree?.call(ptr);
  int sharedBufLenRaw(ffi.Pointer<ffi.Void> ptr) => _sharedBufLen?.call(ptr) ?? 0;
  int sharedBufPtrAddrRaw(ffi.Pointer<ffi.Void> ptr) => _sharedBufPtrAddr?.call(ptr) ?? 0;
  int sharedBufReadByteRaw(ffi.Pointer<ffi.Void> ptr, int offset) =>
      _sharedBufReadByte?.call(ptr, offset) ?? 0;
  void sharedBufWriteByteRaw(ffi.Pointer<ffi.Void> ptr, int offset, int value) =>
      _sharedBufWriteByte?.call(ptr, offset, value);
}
