// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.41.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.0.0-dev.41';

  @override
  int get rustContentHash => -1244947648;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'fluorite_core',
    ioDirectory: '../fluorite_core/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  ConstCChar crateApiEngineEngineStatusCAutoAccessorGetAllocatorName(
      {required EngineStatusC that});

  BigInt crateApiEngineEngineStatusCAutoAccessorGetArenaCapacity(
      {required EngineStatusC that});

  ConstCChar crateApiEngineEngineStatusCAutoAccessorGetCoreVersion(
      {required EngineStatusC that});

  BigInt crateApiEngineEngineStatusCAutoAccessorGetFrameIndex(
      {required EngineStatusC that});

  bool crateApiEngineEngineStatusCAutoAccessorGetIsInitialized(
      {required EngineStatusC that});

  ConstCChar crateApiEngineEngineStatusCAutoAccessorGetStatusMessage(
      {required EngineStatusC that});

  BigInt crateApiEngineEngineStatusCAutoAccessorGetTotalMemoryAllocated(
      {required EngineStatusC that});

  void crateApiEngineEngineStatusCAutoAccessorSetAllocatorName(
      {required EngineStatusC that, required ConstCChar allocatorName});

  void crateApiEngineEngineStatusCAutoAccessorSetArenaCapacity(
      {required EngineStatusC that, required BigInt arenaCapacity});

  void crateApiEngineEngineStatusCAutoAccessorSetCoreVersion(
      {required EngineStatusC that, required ConstCChar coreVersion});

  void crateApiEngineEngineStatusCAutoAccessorSetFrameIndex(
      {required EngineStatusC that, required BigInt frameIndex});

  void crateApiEngineEngineStatusCAutoAccessorSetIsInitialized(
      {required EngineStatusC that, required bool isInitialized});

  void crateApiEngineEngineStatusCAutoAccessorSetStatusMessage(
      {required EngineStatusC that, required ConstCChar statusMessage});

  void crateApiEngineEngineStatusCAutoAccessorSetTotalMemoryAllocated(
      {required EngineStatusC that, required BigInt totalMemoryAllocated});

  Uint8List crateApiEngineAllocateEngineBuffer({required BigInt sizeBytes});

  EngineStatus crateApiEngineGetEngineStatus();

  bool crateApiEngineSharedFrameBufferIsEmpty(
      {required SharedFrameBuffer that});

  BigInt crateApiEngineSharedFrameBufferLen({required SharedFrameBuffer that});

  SharedFrameBuffer crateApiEngineSharedFrameBufferNew(
      {required BigInt sizeBytes});

  BigInt crateApiEngineSharedFrameBufferPtrAddress(
      {required SharedFrameBuffer that});

  int crateApiEngineSharedFrameBufferReadByte(
      {required SharedFrameBuffer that, required BigInt offset});

  void crateApiEngineSharedFrameBufferWriteByte(
      {required SharedFrameBuffer that,
      required BigInt offset,
      required int value});

  EngineStatus crateApiEngineStartEngine();

  bool crateApiEngineVerifyBufferSentinels({required List<int> buffer});

  Future<bool> crateApiEngineVerifyBufferSentinelsSlice(
      {required List<int> buffer});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_EngineStatusC;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_EngineStatusC;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_EngineStatusCPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_SharedFrameBuffer;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_SharedFrameBuffer;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SharedFrameBufferPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ConstCChar;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ConstCChar;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ConstCCharPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ConstCChar crateApiEngineEngineStatusCAutoAccessorGetAllocatorName(
      {required EngineStatusC that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorGetAllocatorNameConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorGetAllocatorNameConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_get_allocator_name",
            argNames: ["that"],
          );

  @override
  BigInt crateApiEngineEngineStatusCAutoAccessorGetArenaCapacity(
      {required EngineStatusC that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_usize,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorGetArenaCapacityConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorGetArenaCapacityConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_get_arena_capacity",
            argNames: ["that"],
          );

  @override
  ConstCChar crateApiEngineEngineStatusCAutoAccessorGetCoreVersion(
      {required EngineStatusC that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorGetCoreVersionConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorGetCoreVersionConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_get_core_version",
            argNames: ["that"],
          );

  @override
  BigInt crateApiEngineEngineStatusCAutoAccessorGetFrameIndex(
      {required EngineStatusC that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineEngineStatusCAutoAccessorGetFrameIndexConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorGetFrameIndexConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_get_frame_index",
            argNames: ["that"],
          );

  @override
  bool crateApiEngineEngineStatusCAutoAccessorGetIsInitialized(
      {required EngineStatusC that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorGetIsInitializedConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorGetIsInitializedConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_get_is_initialized",
            argNames: ["that"],
          );

  @override
  ConstCChar crateApiEngineEngineStatusCAutoAccessorGetStatusMessage(
      {required EngineStatusC that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorGetStatusMessageConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorGetStatusMessageConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_get_status_message",
            argNames: ["that"],
          );

  @override
  BigInt crateApiEngineEngineStatusCAutoAccessorGetTotalMemoryAllocated(
      {required EngineStatusC that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_usize,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorGetTotalMemoryAllocatedConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorGetTotalMemoryAllocatedConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_get_total_memory_allocated",
            argNames: ["that"],
          );

  @override
  void crateApiEngineEngineStatusCAutoAccessorSetAllocatorName(
      {required EngineStatusC that, required ConstCChar allocatorName}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
            allocatorName, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorSetAllocatorNameConstMeta,
      argValues: [that, allocatorName],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorSetAllocatorNameConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_set_allocator_name",
            argNames: ["that", "allocatorName"],
          );

  @override
  void crateApiEngineEngineStatusCAutoAccessorSetArenaCapacity(
      {required EngineStatusC that, required BigInt arenaCapacity}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        sse_encode_usize(arenaCapacity, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorSetArenaCapacityConstMeta,
      argValues: [that, arenaCapacity],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorSetArenaCapacityConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_set_arena_capacity",
            argNames: ["that", "arenaCapacity"],
          );

  @override
  void crateApiEngineEngineStatusCAutoAccessorSetCoreVersion(
      {required EngineStatusC that, required ConstCChar coreVersion}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
            coreVersion, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorSetCoreVersionConstMeta,
      argValues: [that, coreVersion],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorSetCoreVersionConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_set_core_version",
            argNames: ["that", "coreVersion"],
          );

  @override
  void crateApiEngineEngineStatusCAutoAccessorSetFrameIndex(
      {required EngineStatusC that, required BigInt frameIndex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        sse_encode_u_64(frameIndex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineEngineStatusCAutoAccessorSetFrameIndexConstMeta,
      argValues: [that, frameIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorSetFrameIndexConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_set_frame_index",
            argNames: ["that", "frameIndex"],
          );

  @override
  void crateApiEngineEngineStatusCAutoAccessorSetIsInitialized(
      {required EngineStatusC that, required bool isInitialized}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        sse_encode_bool(isInitialized, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorSetIsInitializedConstMeta,
      argValues: [that, isInitialized],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorSetIsInitializedConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_set_is_initialized",
            argNames: ["that", "isInitialized"],
          );

  @override
  void crateApiEngineEngineStatusCAutoAccessorSetStatusMessage(
      {required EngineStatusC that, required ConstCChar statusMessage}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
            statusMessage, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorSetStatusMessageConstMeta,
      argValues: [that, statusMessage],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorSetStatusMessageConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_set_status_message",
            argNames: ["that", "statusMessage"],
          );

  @override
  void crateApiEngineEngineStatusCAutoAccessorSetTotalMemoryAllocated(
      {required EngineStatusC that, required BigInt totalMemoryAllocated}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
            that, serializer);
        sse_encode_usize(totalMemoryAllocated, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiEngineEngineStatusCAutoAccessorSetTotalMemoryAllocatedConstMeta,
      argValues: [that, totalMemoryAllocated],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiEngineEngineStatusCAutoAccessorSetTotalMemoryAllocatedConstMeta =>
          const TaskConstMeta(
            debugName: "EngineStatusC_auto_accessor_set_total_memory_allocated",
            argNames: ["that", "totalMemoryAllocated"],
          );

  @override
  Uint8List crateApiEngineAllocateEngineBuffer({required BigInt sizeBytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_usize(sizeBytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineAllocateEngineBufferConstMeta,
      argValues: [sizeBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineAllocateEngineBufferConstMeta =>
      const TaskConstMeta(
        debugName: "allocate_engine_buffer",
        argNames: ["sizeBytes"],
      );

  @override
  EngineStatus crateApiEngineGetEngineStatus() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_engine_status,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineGetEngineStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineGetEngineStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_engine_status",
        argNames: [],
      );

  @override
  bool crateApiEngineSharedFrameBufferIsEmpty(
      {required SharedFrameBuffer that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_shared_frame_buffer(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineSharedFrameBufferIsEmptyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineSharedFrameBufferIsEmptyConstMeta =>
      const TaskConstMeta(
        debugName: "shared_frame_buffer_is_empty",
        argNames: ["that"],
      );

  @override
  BigInt crateApiEngineSharedFrameBufferLen({required SharedFrameBuffer that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_shared_frame_buffer(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineSharedFrameBufferLenConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineSharedFrameBufferLenConstMeta =>
      const TaskConstMeta(
        debugName: "shared_frame_buffer_len",
        argNames: ["that"],
      );

  @override
  SharedFrameBuffer crateApiEngineSharedFrameBufferNew(
      {required BigInt sizeBytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_usize(sizeBytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_shared_frame_buffer,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineSharedFrameBufferNewConstMeta,
      argValues: [sizeBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineSharedFrameBufferNewConstMeta =>
      const TaskConstMeta(
        debugName: "shared_frame_buffer_new",
        argNames: ["sizeBytes"],
      );

  @override
  BigInt crateApiEngineSharedFrameBufferPtrAddress(
      {required SharedFrameBuffer that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_shared_frame_buffer(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineSharedFrameBufferPtrAddressConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineSharedFrameBufferPtrAddressConstMeta =>
      const TaskConstMeta(
        debugName: "shared_frame_buffer_ptr_address",
        argNames: ["that"],
      );

  @override
  int crateApiEngineSharedFrameBufferReadByte(
      {required SharedFrameBuffer that, required BigInt offset}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_shared_frame_buffer(that, serializer);
        sse_encode_usize(offset, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineSharedFrameBufferReadByteConstMeta,
      argValues: [that, offset],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineSharedFrameBufferReadByteConstMeta =>
      const TaskConstMeta(
        debugName: "shared_frame_buffer_read_byte",
        argNames: ["that", "offset"],
      );

  @override
  void crateApiEngineSharedFrameBufferWriteByte(
      {required SharedFrameBuffer that,
      required BigInt offset,
      required int value}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer(
            that, serializer);
        sse_encode_usize(offset, serializer);
        sse_encode_u_8(value, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineSharedFrameBufferWriteByteConstMeta,
      argValues: [that, offset, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineSharedFrameBufferWriteByteConstMeta =>
      const TaskConstMeta(
        debugName: "shared_frame_buffer_write_byte",
        argNames: ["that", "offset", "value"],
      );

  @override
  EngineStatus crateApiEngineStartEngine() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_engine_status,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineStartEngineConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineStartEngineConstMeta => const TaskConstMeta(
        debugName: "start_engine",
        argNames: [],
      );

  @override
  bool crateApiEngineVerifyBufferSentinels({required List<int> buffer}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(buffer, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineVerifyBufferSentinelsConstMeta,
      argValues: [buffer],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineVerifyBufferSentinelsConstMeta =>
      const TaskConstMeta(
        debugName: "verify_buffer_sentinels",
        argNames: ["buffer"],
      );

  @override
  Future<bool> crateApiEngineVerifyBufferSentinelsSlice(
      {required List<int> buffer}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(buffer, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineVerifyBufferSentinelsSliceConstMeta,
      argValues: [buffer],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineVerifyBufferSentinelsSliceConstMeta =>
      const TaskConstMeta(
        debugName: "verify_buffer_sentinels_slice",
        argNames: ["buffer"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_EngineStatusC => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_EngineStatusC => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_SharedFrameBuffer => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_SharedFrameBuffer => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ConstCChar => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ConstCChar => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char;

  @protected
  EngineStatusC
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineStatusCImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ConstCChar
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConstCCharImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EngineStatusC
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineStatusCImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SharedFrameBuffer
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SharedFrameBufferImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EngineStatusC
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineStatusCImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EngineStatusC
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EngineStatusCImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SharedFrameBuffer
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SharedFrameBufferImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ConstCChar
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConstCCharImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SharedFrameBuffer dco_decode_box_autoadd_shared_frame_buffer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_shared_frame_buffer(raw);
  }

  @protected
  EngineStatus dco_decode_engine_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return EngineStatus(
      isInitialized: dco_decode_bool(arr[0]),
      totalMemoryAllocated: dco_decode_usize(arr[1]),
      arenaCapacity: dco_decode_usize(arr[2]),
      frameIndex: dco_decode_u_64(arr[3]),
      statusMessage: dco_decode_String(arr[4]),
      coreVersion: dco_decode_String(arr[5]),
      allocatorName: dco_decode_String(arr[6]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SharedFrameBuffer dco_decode_shared_frame_buffer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SharedFrameBuffer.raw(
      data: dco_decode_list_prim_u_8_strict(arr[0]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  EngineStatusC
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineStatusCImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ConstCChar
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ConstCCharImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  EngineStatusC
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineStatusCImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  SharedFrameBuffer
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SharedFrameBufferImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  EngineStatusC
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineStatusCImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  EngineStatusC
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EngineStatusCImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  SharedFrameBuffer
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SharedFrameBufferImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ConstCChar
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ConstCCharImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SharedFrameBuffer sse_decode_box_autoadd_shared_frame_buffer(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_shared_frame_buffer(deserializer));
  }

  @protected
  EngineStatus sse_decode_engine_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isInitialized = sse_decode_bool(deserializer);
    var var_totalMemoryAllocated = sse_decode_usize(deserializer);
    var var_arenaCapacity = sse_decode_usize(deserializer);
    var var_frameIndex = sse_decode_u_64(deserializer);
    var var_statusMessage = sse_decode_String(deserializer);
    var var_coreVersion = sse_decode_String(deserializer);
    var var_allocatorName = sse_decode_String(deserializer);
    return EngineStatus(
        isInitialized: var_isInitialized,
        totalMemoryAllocated: var_totalMemoryAllocated,
        arenaCapacity: var_arenaCapacity,
        frameIndex: var_frameIndex,
        statusMessage: var_statusMessage,
        coreVersion: var_coreVersion,
        allocatorName: var_allocatorName);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SharedFrameBuffer sse_decode_shared_frame_buffer(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return SharedFrameBuffer.raw(data: var_data);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          EngineStatusC self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as EngineStatusCImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
          ConstCChar self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ConstCCharImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          EngineStatusC self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as EngineStatusCImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer(
          SharedFrameBuffer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SharedFrameBufferImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          EngineStatusC self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as EngineStatusCImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineStatusC(
          EngineStatusC self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as EngineStatusCImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSharedFrameBuffer(
          SharedFrameBuffer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SharedFrameBufferImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerconstc_char(
          ConstCChar self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ConstCCharImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_shared_frame_buffer(
      SharedFrameBuffer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_shared_frame_buffer(self, serializer);
  }

  @protected
  void sse_encode_engine_status(EngineStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isInitialized, serializer);
    sse_encode_usize(self.totalMemoryAllocated, serializer);
    sse_encode_usize(self.arenaCapacity, serializer);
    sse_encode_u_64(self.frameIndex, serializer);
    sse_encode_String(self.statusMessage, serializer);
    sse_encode_String(self.coreVersion, serializer);
    sse_encode_String(self.allocatorName, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_shared_frame_buffer(
      SharedFrameBuffer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ConstCCharImpl extends RustOpaque implements ConstCChar {
  // Not to be used by end users
  ConstCCharImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ConstCCharImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ConstCChar,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ConstCChar,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ConstCCharPtr,
  );
}

@sealed
class EngineStatusCImpl extends RustOpaque implements EngineStatusC {
  // Not to be used by end users
  EngineStatusCImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  EngineStatusCImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_EngineStatusC,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_EngineStatusC,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_EngineStatusCPtr,
  );

  ConstCChar get allocatorName => RustLib.instance.api
          .crateApiEngineEngineStatusCAutoAccessorGetAllocatorName(
        that: this,
      );

  BigInt get arenaCapacity => RustLib.instance.api
          .crateApiEngineEngineStatusCAutoAccessorGetArenaCapacity(
        that: this,
      );

  ConstCChar get coreVersion => RustLib.instance.api
          .crateApiEngineEngineStatusCAutoAccessorGetCoreVersion(
        that: this,
      );

  BigInt get frameIndex =>
      RustLib.instance.api.crateApiEngineEngineStatusCAutoAccessorGetFrameIndex(
        that: this,
      );

  bool get isInitialized => RustLib.instance.api
          .crateApiEngineEngineStatusCAutoAccessorGetIsInitialized(
        that: this,
      );

  ConstCChar get statusMessage => RustLib.instance.api
          .crateApiEngineEngineStatusCAutoAccessorGetStatusMessage(
        that: this,
      );

  BigInt get totalMemoryAllocated => RustLib.instance.api
          .crateApiEngineEngineStatusCAutoAccessorGetTotalMemoryAllocated(
        that: this,
      );

  void set allocatorName(ConstCChar allocatorName) => RustLib.instance.api
      .crateApiEngineEngineStatusCAutoAccessorSetAllocatorName(
          that: this, allocatorName: allocatorName);

  void set arenaCapacity(BigInt arenaCapacity) => RustLib.instance.api
      .crateApiEngineEngineStatusCAutoAccessorSetArenaCapacity(
          that: this, arenaCapacity: arenaCapacity);

  void set coreVersion(ConstCChar coreVersion) => RustLib.instance.api
      .crateApiEngineEngineStatusCAutoAccessorSetCoreVersion(
          that: this, coreVersion: coreVersion);

  void set frameIndex(BigInt frameIndex) =>
      RustLib.instance.api.crateApiEngineEngineStatusCAutoAccessorSetFrameIndex(
          that: this, frameIndex: frameIndex);

  void set isInitialized(bool isInitialized) => RustLib.instance.api
      .crateApiEngineEngineStatusCAutoAccessorSetIsInitialized(
          that: this, isInitialized: isInitialized);

  void set statusMessage(ConstCChar statusMessage) => RustLib.instance.api
      .crateApiEngineEngineStatusCAutoAccessorSetStatusMessage(
          that: this, statusMessage: statusMessage);

  void set totalMemoryAllocated(BigInt totalMemoryAllocated) => RustLib
      .instance.api
      .crateApiEngineEngineStatusCAutoAccessorSetTotalMemoryAllocated(
          that: this, totalMemoryAllocated: totalMemoryAllocated);
}

@sealed
class SharedFrameBufferImpl extends RustOpaque implements SharedFrameBuffer {
  // Not to be used by end users
  SharedFrameBufferImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SharedFrameBufferImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SharedFrameBuffer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SharedFrameBuffer,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_SharedFrameBufferPtr,
  );

  /// Returns true if the buffer has zero length.
  bool isEmpty() => RustLib.instance.api.crateApiEngineSharedFrameBufferIsEmpty(
        that: this,
      );

  /// Length of the buffer in bytes.
  BigInt len() => RustLib.instance.api.crateApiEngineSharedFrameBufferLen(
        that: this,
      );

  /// Raw native memory pointer address as `usize` for direct Dart FFI `Pointer.fromAddress()`.
  BigInt ptrAddress() =>
      RustLib.instance.api.crateApiEngineSharedFrameBufferPtrAddress(
        that: this,
      );

  /// Reads the byte at the specified offset with safe bounds checking.
  int readByte({required BigInt offset}) => RustLib.instance.api
      .crateApiEngineSharedFrameBufferReadByte(that: this, offset: offset);

  /// Writes a byte at the specified offset with safe bounds checking.
  void writeByte({required BigInt offset, required int value}) =>
      RustLib.instance.api.crateApiEngineSharedFrameBufferWriteByte(
          that: this, offset: offset, value: value);
}
