name: fluorescent_flame
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.4.0
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.38.2
  fluorescent_core:
    path: ../fluorescent_core
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.6.2+hotfix.3
  web_socket_channel: ^3.0.3

dev_dependencies:
  flame_test: ^2.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
