name: fluorescent_flame
description: fluorescent_flame package for Fluorescent.
version: 0.1.0
environment:
  sdk: ">=3.5.0 <4.0.0"
resolution: workspace
dependencies:
  flame: ^1.10.0
  flutter:
    sdk: flutter
