// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../allocator.dart';
import '../frb_generated.dart';
import '../lib.dart';
import 'arena.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `alloc_slice`, `alloc`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DoubleBufferedFrameAllocator>>
abstract class DoubleBufferedFrameAllocator
    implements RustOpaqueInterface, CustomAllocator {
  /// Allocates a contiguous 1MB buffer with sentinels in the current active frame arena.
  Future<void> alloc1MbBuffer();

  Future<MutU8> allocRaw({required Layout layout});

  Future<BigInt> allocatedBytes();

  /// Returns allocation count in the active frame arena.
  Future<BigInt> allocationCount();

  Future<BigInt> capacityBytes();

  /// Returns a reference to the active arena for the current frame.
  Future<void> currentArena();

  /// Returns the raw active arena index (0 or 1).
  Future<BigInt> currentIndex();

  /// Returns the monotonic frame count since initialization.
  Future<BigInt> frameIndex();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new `DoubleBufferedFrameAllocator` where each frame buffer has `per_frame_capacity` bytes.
  static Future<DoubleBufferedFrameAllocator> newInstance(
          {required BigInt perFrameCapacity}) =>
      RustLib.instance.api.crateAllocatorFrameDoubleBufferedFrameAllocatorNew(
          perFrameCapacity: perFrameCapacity);

  /// Returns a reference to the previous frame's arena (retaining frame N-1 data).
  Future<void> previousArena();

  /// Returns remaining bytes in the active frame arena.
  Future<BigInt> remainingBytes();

  Future<void> reset();

  /// Swaps the active ping-pong buffers:
  /// 1. Increments the frame counter.
  /// 2. Alternates the active arena index (0 -> 1 -> 0).
  /// 3. Resets the incoming arena in O(1) so it is ready for fresh allocations.
  Future<void> swapBuffers();

  /// Swaps buffers without resetting the new buffer (useful for inspection or custom recycling).
  Future<void> swapBuffersNoReset();
}
