// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`


            RaftCluster  initializeRaftCluster() => RustLib.instance.api.crateOrchestrationRaftInitializeRaftCluster();

RaftCluster  addNodeToCluster({required RaftCluster cluster , required String id , required double hScore }) => RustLib.instance.api.crateOrchestrationRaftAddNodeToCluster(cluster: cluster, id: id, hScore: hScore);


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RaftCluster>>
                abstract class RaftCluster implements RustOpaqueInterface {
                     Future<void>  addNode({required String id , required double hScore });


 Future<void>  electLeader();


  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
static Future<RaftCluster>  newInstance()=>RustLib.instance.api.crateOrchestrationRaftRaftClusterNew();


 Future<String?>  routeJob({required double jobComplexity });




                }


class ClusterNode  {
                final String id;
final NodeRole role;
final double hScore;

                const ClusterNode({required this.id ,required this.role ,required this.hScore ,});





        @override
        int get hashCode => id.hashCode^role.hashCode^hScore.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ClusterNode &&
                runtimeType == other.runtimeType
                && id == other.id&& role == other.role&& hScore == other.hScore;

            }

enum NodeRole {
                    leader,
worker,
candidate,
                    ;

                }

class RaftCluster  {
                final List<ClusterNode> nodes;
final BigInt currentTerm;

                const RaftCluster({required this.nodes ,required this.currentTerm ,});

                 Future<void>  addNode({required String id , required double hScore })=>RustLib.instance.api.crateOrchestrationRaftRaftClusterAddNode(that: this, id: id, hScore: hScore);


 Future<void>  electLeader()=>RustLib.instance.api.crateOrchestrationRaftRaftClusterElectLeader(that: this, );


  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
static Future<RaftCluster>  newInstance()=>RustLib.instance.api.crateOrchestrationRaftRaftClusterNew();


 Future<String?>  routeJob({required double jobComplexity })=>RustLib.instance.api.crateOrchestrationRaftRaftClusterRouteJob(that: this, jobComplexity: jobComplexity);





        @override
        int get hashCode => nodes.hashCode^currentTerm.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is RaftCluster &&
                runtimeType == other.runtimeType
                && nodes == other.nodes&& currentTerm == other.currentTerm;

            }
