// This file is automatically generated by flutter_rust_bridge v2, so please do not edit it.
// [@generated by flutter_rust_bridge]

#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy
)]

use crate::api::engine::{
    allocate_engine_buffer, get_engine_status, start_engine, verify_buffer_sentinels,
    EngineStatus, SharedFrameBuffer,
};

// Section: wire_funcs

/// C-ABI initialization entry point for the Flutter Rust Bridge v2 runtime.
#[no_mangle]
pub extern "C" fn frb_initialize_rust(
    _dart_opaque_drop_port: i64,
    _dart_fn_data_drop_port: i64,
) {
    // Flutter Rust Bridge runtime initialization hook
}

/// C-ABI wire function for starting the engine lifecycle asynchronously/via message port.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__start_engine(
    port_: i64,
    ptr_: *mut u8,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    let _ = (port_, ptr_, rust_vec_len_, data_len_);
    let _ = start_engine();
}

/// C-ABI synchronous wire function for starting the engine lifecycle.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__start_engine_sync() -> *mut EngineStatus {
    let status = start_engine();
    Box::into_raw(Box::new(status))
}

/// C-ABI synchronous wire function for allocating a contiguous engine buffer.
///
/// In FRB v2, continuous byte arrays are mapped directly to Dart's external TypedData
/// (`Dart_NewExternalTypedDataWithFinalizer`), achieving zero-copy transfer.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__allocate_engine_buffer(
    size_bytes: usize,
) -> *mut u8 {
    let mut buf = allocate_engine_buffer(size_bytes);
    let ptr = buf.as_mut_ptr();
    std::mem::forget(buf);
    ptr
}

/// C-ABI wire function to deallocate memory returned by `allocate_engine_buffer`.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__free_engine_buffer(
    ptr: *mut u8,
    size_bytes: usize,
) {
    if !ptr.is_null() && size_bytes > 0 {
        unsafe {
            let _ = Vec::from_raw_parts(ptr, size_bytes, size_bytes);
        }
    }
}

/// C-ABI wire function for retrieving engine telemetry status.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__get_engine_status() -> *mut EngineStatus {
    let status = get_engine_status();
    Box::into_raw(Box::new(status))
}

/// C-ABI wire function for freeing an allocated `EngineStatus` struct.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__free_engine_status(ptr: *mut EngineStatus) {
    if !ptr.is_null() {
        unsafe {
            let _ = Box::from_raw(ptr);
        }
    }
}

/// C-ABI wire function for verifying buffer sentinels.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__verify_buffer_sentinels(
    ptr: *const u8,
    len: usize,
) -> bool {
    if ptr.is_null() || len == 0 {
        return false;
    }
    let slice = unsafe { std::slice::from_raw_parts(ptr, len) };
    verify_buffer_sentinels(slice.to_vec())
}

/// C-ABI wire function for creating a new `SharedFrameBuffer`.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__shared_frame_buffer_new(
    size_bytes: usize,
) -> *mut SharedFrameBuffer {
    let handle = SharedFrameBuffer::new(size_bytes);
    Box::into_raw(Box::new(handle))
}

/// C-ABI wire function for freeing a `SharedFrameBuffer`.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__shared_frame_buffer_free(
    ptr: *mut SharedFrameBuffer,
) {
    if !ptr.is_null() {
        unsafe {
            let _ = Box::from_raw(ptr);
        }
    }
}

/// C-ABI wire function for querying the byte length of a `SharedFrameBuffer`.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__shared_frame_buffer_len(
    ptr: *const SharedFrameBuffer,
) -> usize {
    if ptr.is_null() {
        0
    } else {
        unsafe { (*ptr).len() }
    }
}

/// C-ABI wire function for querying the raw pointer address of a `SharedFrameBuffer`.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__shared_frame_buffer_ptr_address(
    ptr: *const SharedFrameBuffer,
) -> usize {
    if ptr.is_null() {
        0
    } else {
        unsafe { (*ptr).ptr_address() }
    }
}

/// C-ABI wire function for reading a byte at a given offset from a `SharedFrameBuffer`.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__shared_frame_buffer_read_byte(
    ptr: *const SharedFrameBuffer,
    offset: usize,
) -> u8 {
    if ptr.is_null() {
        0
    } else {
        unsafe { (*ptr).read_byte(offset) }
    }
}

/// C-ABI wire function for writing a byte at a given offset into a `SharedFrameBuffer`.
#[no_mangle]
pub extern "C" fn wire__crate__api__engine__shared_frame_buffer_write_byte(
    ptr: *mut SharedFrameBuffer,
    offset: usize,
    value: u8,
) {
    if !ptr.is_null() {
        unsafe { (*ptr).write_byte(offset, value) }
    }
}
