// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`


            PhysicsServerStatus  startPhysicsServer() => RustLib.instance.api.crateServersPhysicsStartPhysicsServer();

            class PhysicsServerStatus  {
                final bool isRunning;
final BigInt activeBodies;

                const PhysicsServerStatus({required this.isRunning ,required this.activeBodies ,});





        @override
        int get hashCode => isRunning.hashCode^activeBodies.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PhysicsServerStatus &&
                runtimeType == other.runtimeType
                && isRunning == other.isRunning&& activeBodies == other.activeBodies;

            }
