use std::sync::Arc;

/// Entity instance data sent directly to the GPU buffer via `fluoderpod`.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct EntityInstance {
    pub transform: [[f32; 4]; 4], // 64 bytes: 4x4 World Model Matrix
    pub color_tint: [f32; 4],     // 16 bytes: RGBA color modifier
    pub cluster_id: u32,          // 4 bytes: Index to Virtual Geometry Cluster
    pub flags: u32,               // 4 bytes: Visibility, team, status flags
    pub _padding: [f32; 2],       // 8 bytes: 96-byte alignment
}

/// Unified GPU Command Buffer architecture.
pub struct PipelineManager {
    pub device: Arc<wgpu::Device>,
    pub queue: Arc<wgpu::Queue>,
    pub entity_buffer: Option<wgpu::Buffer>,
    pub indirect_draw_buffer: Option<wgpu::Buffer>,
    pub render_pipeline: Option<wgpu::RenderPipeline>,
}

impl PipelineManager {
    pub fn new(
        device: Arc<wgpu::Device>,
        queue: Arc<wgpu::Queue>,
        entity_buffer: Option<wgpu::Buffer>,
        indirect_draw_buffer: Option<wgpu::Buffer>,
        render_pipeline: Option<wgpu::RenderPipeline>,
    ) -> Self {
        Self {
            device,
            queue,
            entity_buffer,
            indirect_draw_buffer,
            render_pipeline,
        }
    }

    /// Allocates or updates the GPU buffer receiving the `fluoderpod` batch.
    pub fn update_entity_buffer(&mut self, data: &[u8]) {
        if let Some(ref buffer) = self.entity_buffer {
            self.queue.write_buffer(buffer, 0, data);
        }
    }

    /// Submits the final indirect draw commands generated by the compute passes.
    pub fn submit_indirect_draws<'a>(&'a self, render_pass: &mut wgpu::RenderPass<'a>) {
        if let (Some(pipeline), Some(indirect_buf)) = (&self.render_pipeline, &self.indirect_draw_buffer) {
            render_pass.set_pipeline(pipeline);
            render_pass.draw_indexed_indirect(indirect_buf, 0);
        }
    }
}
