use std::sync::Arc;

/// Unified GPU Command Buffer architecture.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PackedEntityInstance {
    pub position: [f32; 3],          // 12 bytes (Sphere center)
    pub sphere_radius: f32,          // 4 bytes  (Culling radius)
    pub rotation_quat: [f32; 4],     // 16 bytes (Orientation)
    pub scale: [f32; 3],             // 12 bytes (Non-uniform scale)
    pub cluster_and_flags: u32,      // 4 bytes  (24-bit cluster_id | 8-bit flags)
}

// Compile-time assertion to guarantee the exact 48-byte memory layout
const _: () = assert!(std::mem::size_of::<PackedEntityInstance>() == 48);

pub struct PipelineManager {
    pub device: Arc<wgpu::Device>,
    pub queue: Arc<wgpu::Queue>,
    pub entity_buffer: Option<wgpu::Buffer>,
    pub indirect_draw_buffer: Option<wgpu::Buffer>,
    pub render_pipeline: Option<wgpu::RenderPipeline>,
}

impl PipelineManager {
    pub fn new(
        device: Arc<wgpu::Device>,
        queue: Arc<wgpu::Queue>,
        entity_buffer: Option<wgpu::Buffer>,
        indirect_draw_buffer: Option<wgpu::Buffer>,
        render_pipeline: Option<wgpu::RenderPipeline>,
    ) -> Self {
        Self {
            device,
            queue,
            entity_buffer,
            indirect_draw_buffer,
            render_pipeline,
        }
    }

    /// Allocates or updates the GPU buffer receiving the `fluoderpod` batch.
    pub fn update_entity_buffer(&mut self, data: &[u8]) {
        if let Some(ref buffer) = self.entity_buffer {
            self.queue.write_buffer(buffer, 0, data);
        }
    }

    /// Submits the final indirect draw commands generated by the compute passes.
    pub fn submit_indirect_draws<'a>(&'a self, render_pass: &mut wgpu::RenderPass<'a>) {
        if let (Some(pipeline), Some(indirect_buf)) = (&self.render_pipeline, &self.indirect_draw_buffer) {
            render_pass.set_pipeline(pipeline);
            render_pass.draw_indexed_indirect(indirect_buf, 0);
        }
    }
}
