// This file is automatically generated by flutter_rust_bridge v2, so please do not edit it.
// [@generated by flutter_rust_bridge]
// ignore_for_file: unused_import, unused_element, unused_field

import 'dart:ffi' as ffi;
import 'dart:typed_data';

import '../frb_generated.dart';

/// Telemetry status returned across the FFI boundary from the Rust core engine.
class EngineStatus {
  final bool isInitialized;
  final BigInt totalMemoryAllocated;
  final BigInt arenaCapacity;
  final BigInt frameIndex;
  final String statusMessage;
  final String coreVersion;
  final String allocatorName;

  const EngineStatus({
    required this.isInitialized,
    required this.totalMemoryAllocated,
    required this.arenaCapacity,
    required this.frameIndex,
    required this.statusMessage,
    this.coreVersion = '0.1.0',
    this.allocatorName = 'FluoriteArenaAllocator_v1',
  });

  @override
  String toString() =>
      'EngineStatus(init: $isInitialized, mem: $totalMemoryAllocated, cap: $arenaCapacity, frame: $frameIndex, msg: $statusMessage)';
}

/// Initializes the engine native subsystems and custom memory allocators.
EngineStatus startEngine() {
  return RustLib.instance.api.crateApiEngineStartEngine();
}

/// Allocates a contiguous buffer of `sizeBytes` in Rust memory,
/// with sentinels (0xAA at index 0, 0x55 at index `sizeBytes - 1`),
/// returned as a zero-copy Uint8List.
///
/// Accepts either `BigInt` or `int` for `sizeBytes`.
Uint8List allocateEngineBuffer({required dynamic sizeBytes}) {
  final count = sizeBytes is BigInt ? sizeBytes.toInt() : (sizeBytes as int);
  return RustLib.instance.api.crateApiEngineAllocateEngineBuffer(sizeBytes: count);
}

/// Returns the current runtime telemetry and memory status of the engine.
EngineStatus getEngineStatus() {
  return RustLib.instance.api.crateApiEngineGetEngineStatus();
}

/// Verifies whether the provided buffer contains valid 0xAA header and 0x55 footer sentinels.
bool verifyBufferSentinels({required List<int> buffer}) {
  return RustLib.instance.api.crateApiEngineVerifyBufferSentinels(buffer: buffer);
}

/// Persistent shared frame buffer handle exposing raw native pointer address (`int`)
/// and length for direct Dart `Pointer.asTypedList()` live view.
class SharedFrameBuffer implements ffi.Finalizable {
  final int _ptrAddress;
  final int _len;
  final Uint8List _view;

  SharedFrameBuffer.fromView(this._ptrAddress, this._len, this._view);

  factory SharedFrameBuffer({required int sizeBytes}) {
    return RustLib.instance.api.crateApiEngineSharedFrameBufferNew(sizeBytes: sizeBytes);
  }

  static SharedFrameBuffer newInstance({required int sizeBytes}) {
    return SharedFrameBuffer(sizeBytes: sizeBytes);
  }

  int len() => _len;
  bool isEmpty() => _len == 0;
  int ptrAddress() => _ptrAddress;

  int readByte({required int offset}) {
    if (offset >= _len) {
      throw RangeError.index(offset, _view);
    }
    return _view[offset];
  }

  void writeByte({required int offset, required int value}) {
    if (offset >= _len) {
      throw RangeError.index(offset, _view);
    }
    _view[offset] = value;
  }

  /// Live TypedData view over the native memory buffer.
  Uint8List asTypedList() => _view;
}
