// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Initializes the Fluorite Engine native subsystems and custom allocators.
EngineStatus startEngine({EngineConfig? config}) =>
    RustLib.instance.api.crateApiEngineStartEngine(config: config);

/// Draws a wireframe primitive in the 3D space.
void drawWireframe(
        {required List<double> transform,
        required int color,
        required double thickness}) =>
    RustLib.instance.api.crateApiEngineDrawWireframe(
        transform: transform, color: color, thickness: thickness);

/// Allocates a contiguous buffer of `size_bytes` using the custom `ArenaAllocator`.
///
/// Sets 0xAA sentinel at index 0 and 0x55 sentinel at index `size_bytes - 1`, and returns `Vec<u8>`.
/// In FRB v2, `Vec<u8>` is transferred to Dart zero-copy via the Dart VM's
/// `Dart_NewExternalTypedDataWithFinalizer` as `Uint8List` without serialization overhead.
Uint8List allocateEngineBuffer({required BigInt sizeBytes}) =>
    RustLib.instance.api
        .crateApiEngineAllocateEngineBuffer(sizeBytes: sizeBytes);

/// Returns the current runtime telemetry and memory status of the engine.
EngineStatus getEngineStatus() =>
    RustLib.instance.api.crateApiEngineGetEngineStatus();

/// Verifies whether the provided buffer contains valid 1MB sentinel boundaries.
bool verifyBufferSentinels({required List<int> buffer}) =>
    RustLib.instance.api.crateApiEngineVerifyBufferSentinels(buffer: buffer);

/// Helper slice-based sentinel verifier for internal Rust callers.
Future<bool> verifyBufferSentinelsSlice({required List<int> buffer}) =>
    RustLib.instance.api
        .crateApiEngineVerifyBufferSentinelsSlice(buffer: buffer);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CStringPtr>>
abstract class CStringPtr implements RustOpaqueInterface {
  ConstCChar get field0;

  set field0(ConstCChar field0);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EngineStatusC>>
abstract class EngineStatusC implements RustOpaqueInterface {
  CStringPtr get allocatorName;

  BigInt get arenaCapacity;

  CStringPtr get coreVersion;

  BigInt get frameIndex;

  bool get isInitialized;

  CStringPtr get statusMessage;

  BigInt get totalMemoryAllocated;

  set allocatorName(CStringPtr allocatorName);

  set arenaCapacity(BigInt arenaCapacity);

  set coreVersion(CStringPtr coreVersion);

  set frameIndex(BigInt frameIndex);

  set isInitialized(bool isInitialized);

  set statusMessage(CStringPtr statusMessage);

  set totalMemoryAllocated(BigInt totalMemoryAllocated);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SharedFrameBuffer>>
abstract class SharedFrameBuffer implements RustOpaqueInterface {
  Uint8List get data;

  set data(Uint8List data);

  /// Returns true if the buffer has zero length.
  bool isEmpty();

  /// Length of the buffer in bytes.
  BigInt len();

  /// Creates a new `SharedFrameBuffer` of `size_bytes`.
  ///
  /// Initializes with 0xDEADBEEF test header if size >= 4.
  factory SharedFrameBuffer({required BigInt sizeBytes}) => RustLib.instance.api
      .crateApiEngineSharedFrameBufferNew(sizeBytes: sizeBytes);

  /// Raw native memory pointer address as `usize` for direct Dart FFI `Pointer.fromAddress()`.
  BigInt ptrAddress();

  /// Reads the byte at the specified offset with safe bounds checking.
  int readByte({required BigInt offset});

  /// Writes a byte at the specified offset with safe bounds checking.
  void writeByte({required BigInt offset, required int value});
}

class EngineConfig {
  final int resolutionWidth;
  final int resolutionHeight;
  final int hardwareTier;
  final String renderBackend;

  const EngineConfig({
    required this.resolutionWidth,
    required this.resolutionHeight,
    required this.hardwareTier,
    required this.renderBackend,
  });

  @override
  int get hashCode =>
      resolutionWidth.hashCode ^
      resolutionHeight.hashCode ^
      hardwareTier.hashCode ^
      renderBackend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineConfig &&
          runtimeType == other.runtimeType &&
          resolutionWidth == other.resolutionWidth &&
          resolutionHeight == other.resolutionHeight &&
          hardwareTier == other.hardwareTier &&
          renderBackend == other.renderBackend;
}

/// Telemetry and lifecycle snapshot of the Fluorite AAA Engine core.
class EngineStatus {
  /// Whether the engine core subsystems and memory allocators are initialized.
  final bool isInitialized;

  /// Total bytes allocated in the active frame arena.
  final BigInt totalMemoryAllocated;

  /// Usable capacity per frame arena.
  final BigInt arenaCapacity;

  /// Current monotonic engine frame index.
  final BigInt frameIndex;

  /// Informational status message.
  final String statusMessage;

  /// Engine version string.
  final String coreVersion;

  /// Memory allocator subsystem name.
  final String allocatorName;

  /// An optional texture ID returned after native initialization.
  final PlatformInt64? textureId;

  const EngineStatus({
    required this.isInitialized,
    required this.totalMemoryAllocated,
    required this.arenaCapacity,
    required this.frameIndex,
    required this.statusMessage,
    required this.coreVersion,
    required this.allocatorName,
    this.textureId,
  });

  @override
  int get hashCode =>
      isInitialized.hashCode ^
      totalMemoryAllocated.hashCode ^
      arenaCapacity.hashCode ^
      frameIndex.hashCode ^
      statusMessage.hashCode ^
      coreVersion.hashCode ^
      allocatorName.hashCode ^
      textureId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineStatus &&
          runtimeType == other.runtimeType &&
          isInitialized == other.isInitialized &&
          totalMemoryAllocated == other.totalMemoryAllocated &&
          arenaCapacity == other.arenaCapacity &&
          frameIndex == other.frameIndex &&
          statusMessage == other.statusMessage &&
          coreVersion == other.coreVersion &&
          allocatorName == other.allocatorName &&
          textureId == other.textureId;
}
