// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.41.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initializes the Fluorite Engine native subsystems and custom allocators.
EngineStatus startEngine() => RustLib.instance.api.crateApiEngineStartEngine();

/// Allocates a contiguous buffer of `size_bytes` using the custom `ArenaAllocator`.
///
/// Sets 0xAA sentinel at index 0 and 0x55 sentinel at index `size_bytes - 1`, and returns `Vec<u8>`.
/// In FRB v2, `Vec<u8>` is transferred to Dart zero-copy via the Dart VM's
/// `Dart_NewExternalTypedDataWithFinalizer` as `Uint8List` without serialization overhead.
Uint8List allocateEngineBuffer({required BigInt sizeBytes}) =>
    RustLib.instance.api
        .crateApiEngineAllocateEngineBuffer(sizeBytes: sizeBytes);

/// Returns the current runtime telemetry and memory status of the engine.
EngineStatus getEngineStatus() =>
    RustLib.instance.api.crateApiEngineGetEngineStatus();

/// Verifies whether the provided buffer contains valid 1MB sentinel boundaries.
bool verifyBufferSentinels({required List<int> buffer}) =>
    RustLib.instance.api.crateApiEngineVerifyBufferSentinels(buffer: buffer);

/// Helper slice-based sentinel verifier for internal Rust callers.
Future<bool> verifyBufferSentinelsSlice({required List<int> buffer}) =>
    RustLib.instance.api
        .crateApiEngineVerifyBufferSentinelsSlice(buffer: buffer);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EngineStatusC>>
abstract class EngineStatusC implements RustOpaqueInterface {
  ConstCChar get allocatorName;

  BigInt get arenaCapacity;

  ConstCChar get coreVersion;

  BigInt get frameIndex;

  bool get isInitialized;

  ConstCChar get statusMessage;

  BigInt get totalMemoryAllocated;

  void set allocatorName(ConstCChar allocatorName);

  void set arenaCapacity(BigInt arenaCapacity);

  void set coreVersion(ConstCChar coreVersion);

  void set frameIndex(BigInt frameIndex);

  void set isInitialized(bool isInitialized);

  void set statusMessage(ConstCChar statusMessage);

  void set totalMemoryAllocated(BigInt totalMemoryAllocated);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SharedFrameBuffer>>
abstract class SharedFrameBuffer implements RustOpaqueInterface {
  /// Returns true if the buffer has zero length.
  bool isEmpty();

  /// Length of the buffer in bytes.
  BigInt len();

  /// Creates a new `SharedFrameBuffer` of `size_bytes`.
  ///
  /// Initializes with 0xDEADBEEF test header if size >= 4.
  factory SharedFrameBuffer({required BigInt sizeBytes}) => RustLib.instance.api
      .crateApiEngineSharedFrameBufferNew(sizeBytes: sizeBytes);

  /// Raw native memory pointer address as `usize` for direct Dart FFI `Pointer.fromAddress()`.
  BigInt ptrAddress();

  /// Reads the byte at the specified offset with safe bounds checking.
  int readByte({required BigInt offset});

  /// Writes a byte at the specified offset with safe bounds checking.
  void writeByte({required BigInt offset, required int value});
}

/// Telemetry and lifecycle snapshot of the Fluorite AAA Engine core.
class EngineStatus {
  /// Whether the engine core subsystems and memory allocators are initialized.
  final bool isInitialized;

  /// Total bytes allocated in the active frame arena.
  final BigInt totalMemoryAllocated;

  /// Usable capacity per frame arena.
  final BigInt arenaCapacity;

  /// Current monotonic engine frame index.
  final BigInt frameIndex;

  /// Informational status message.
  final String statusMessage;

  /// Engine version string.
  final String coreVersion;

  /// Memory allocator subsystem name.
  final String allocatorName;

  const EngineStatus({
    required this.isInitialized,
    required this.totalMemoryAllocated,
    required this.arenaCapacity,
    required this.frameIndex,
    required this.statusMessage,
    required this.coreVersion,
    required this.allocatorName,
  });

  @override
  int get hashCode =>
      isInitialized.hashCode ^
      totalMemoryAllocated.hashCode ^
      arenaCapacity.hashCode ^
      frameIndex.hashCode ^
      statusMessage.hashCode ^
      coreVersion.hashCode ^
      allocatorName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineStatus &&
          runtimeType == other.runtimeType &&
          isInitialized == other.isInitialized &&
          totalMemoryAllocated == other.totalMemoryAllocated &&
          arenaCapacity == other.arenaCapacity &&
          frameIndex == other.frameIndex &&
          statusMessage == other.statusMessage &&
          coreVersion == other.coreVersion &&
          allocatorName == other.allocatorName;
}

/// Persistent shared frame buffer handle exposing raw pointer address (`usize`)
/// and length for direct Dart `Pointer.asTypedList()` live view.
class SharedFrameBuffer {
  final Uint8List data;

  const SharedFrameBuffer.raw({
    required this.data,
  });

  /// Returns true if the buffer has zero length.
  bool isEmpty() => RustLib.instance.api.crateApiEngineSharedFrameBufferIsEmpty(
        that: this,
      );

  /// Length of the buffer in bytes.
  BigInt len() => RustLib.instance.api.crateApiEngineSharedFrameBufferLen(
        that: this,
      );

  /// Creates a new `SharedFrameBuffer` of `size_bytes`.
  ///
  /// Initializes with 0xDEADBEEF test header if size >= 4.
  factory SharedFrameBuffer({required BigInt sizeBytes}) => RustLib.instance.api
      .crateApiEngineSharedFrameBufferNew(sizeBytes: sizeBytes);

  /// Raw native memory pointer address as `usize` for direct Dart FFI `Pointer.fromAddress()`.
  BigInt ptrAddress() =>
      RustLib.instance.api.crateApiEngineSharedFrameBufferPtrAddress(
        that: this,
      );

  /// Reads the byte at the specified offset with safe bounds checking.
  int readByte({required BigInt offset}) => RustLib.instance.api
      .crateApiEngineSharedFrameBufferReadByte(that: this, offset: offset);

  /// Writes a byte at the specified offset with safe bounds checking.
  void writeByte({required BigInt offset, required int value}) =>
      RustLib.instance.api.crateApiEngineSharedFrameBufferWriteByte(
          that: this, offset: offset, value: value);

  @override
  int get hashCode => data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharedFrameBuffer &&
          runtimeType == other.runtimeType &&
          data == other.data;
}
